# Generated by Django 5.1.4 on 2025-02-14 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('fname', models.TextField(blank=True, null=True)),
                ('dob', models.TextField(blank=True, null=True)),
                ('addr', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('cno', models.TextField(blank=True, null=True)),
                ('pgroup', models.TextField(blank=True, null=True)),
                ('course', models.TextField(blank=True, null=True)),
                ('dept', models.TextField(blank=True, null=True)),
                ('caste', models.TextField(blank=True, null=True)),
                ('rel', models.TextField(blank=True, null=True)),
                ('img', models.FileField(upload_to='upload/')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField(blank=True, null=True)),
                ('deg', models.TextField(blank=True, null=True)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField(blank=True, null=True)),
                ('deg', models.TextField(blank=True, null=True)),
                ('dept', models.TextField(blank=True, null=True)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
