# Generated by Django 5.1.4 on 2025-02-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0002_admission_deg'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='bat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
