# Generated by Django 5.1.4 on 2025-02-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0003_admission_bat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('dob', models.TextField(blank=True, null=True)),
                ('addr', models.TextField(blank=True, null=True)),
                ('cno', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('quali', models.TextField(blank=True, null=True)),
                ('dept', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
