# Generated by Django 5.1.4 on 2025-02-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0004_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField(blank=True, null=True)),
                ('deg', models.TextField(blank=True, null=True)),
                ('dept', models.TextField(blank=True, null=True)),
                ('bat', models.TextField(blank=True, null=True)),
                ('tno', models.TextField(blank=True, null=True)),
                ('pno', models.TextField(blank=True, null=True)),
                ('t1', models.TextField(blank=True, null=True)),
                ('t2', models.TextField(blank=True, null=True)),
                ('t3', models.TextField(blank=True, null=True)),
                ('t4', models.TextField(blank=True, null=True)),
                ('t5', models.TextField(blank=True, null=True)),
                ('p1', models.TextField(blank=True, null=True)),
                ('p2', models.TextField(blank=True, null=True)),
                ('p3', models.TextField(blank=True, null=True)),
                ('p4', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
