# Generated by Django 5.1.4 on 2025-02-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0005_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='yr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
