# Generated by Django 5.1.4 on 2025-02-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0006_subject_sm_subject_yr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sm',
            new_name='sem',
        ),
    ]
