# Generated by Django 5.1.4 on 2025-02-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0007_rename_sm_subject_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='p1',
            field=models.TextField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='p2',
            field=models.TextField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='p3',
            field=models.TextField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='p4',
            field=models.TextField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='t1',
            field=models.TextField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='t2',
            field=models.TextField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='t3',
            field=models.TextField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='t4',
            field=models.TextField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='t5',
            field=models.TextField(default='-', null=True),
        ),
    ]
