# Generated by Django 5.1.4 on 2025-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0008_alter_subject_p1_alter_subject_p2_alter_subject_p3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='p1',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='p2',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='p3',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='p4',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='t1',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='t2',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='t3',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='t4',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='t5',
            field=models.TextField(blank=True, default='-'),
        ),
    ]
