# Generated by Django 5.1.4 on 2025-02-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0009_alter_subject_p1_alter_subject_p2_alter_subject_p3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='bat',
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt1', models.TextField(blank=True, default='-')),
                ('mt2', models.TextField(blank=True, default='-')),
                ('mt3', models.TextField(blank=True, default='-')),
                ('mt4', models.TextField(blank=True, default='-')),
                ('mt5', models.TextField(blank=True, default='-')),
                ('mp1', models.TextField(blank=True, default='-')),
                ('mp2', models.TextField(blank=True, default='-')),
                ('mp3', models.TextField(blank=True, default='-')),
                ('mp4', models.TextField(blank=True, default='-')),
                ('yr', models.TextField(blank=True, null=True)),
                ('sem', models.TextField(blank=True, null=True)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.admission')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.subject')),
            ],
        ),
    ]
