# Generated by Django 5.1.4 on 2025-02-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0010_remove_subject_bat_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='bat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
