# Generated by Django 5.1.4 on 2025-02-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0011_mark_bat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='course',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='deg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='dept',
            field=models.TextField(blank=True, null=True),
        ),
    ]
