# Generated by Django 5.1.4 on 2025-02-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0012_mark_course_mark_deg_mark_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='ano',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
