# Generated by Django 5.1.4 on 2025-02-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0013_admission_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholor', models.TextField(blank=True, default='-')),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.admission')),
            ],
        ),
    ]
