# Generated by Django 5.1.4 on 2025-02-15 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0014_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
