# Generated by Django 5.1.4 on 2025-02-18 11:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0015_scholarship_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.admission')),
            ],
        ),
        migrations.RemoveField(
            model_name='mark',
            name='add',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='add',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
