# Generated by Django 5.1.4 on 2025-02-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0016_attendance_remove_mark_add_remove_mark_sub_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='add',
            new_name='admission',
        ),
    ]
