# Generated by Django 5.1.4 on 2025-02-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0017_rename_add_attendance_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
