# Generated by Django 5.1.4 on 2025-02-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0018_settime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settime',
            name='tm',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
