# Generated by Django 5.1.4 on 2025-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0020_alter_settime_tm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settime',
            name='tm',
            field=models.TextField(blank=True, null=True),
        ),
    ]
