# Generated by Django 5.1.4 on 2025-03-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0024_attendance_batch_attendance_course_attendance_deg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='dt1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
