# Generated by Django 5.1.7 on 2025-03-29 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0025_attendance_dt1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='dt',
        ),
        migrations.AddField(
            model_name='department',
            name='created_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
