# Generated by Django 5.1.7 on 2025-03-29 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0026_remove_degree_dt_department_created_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='created_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='degree',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
