# Generated by Django 5.1.7 on 2025-03-29 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0027_degree_created_dt_degree_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='created_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
